server:
  port: 8001
spring:
  application:
    name: cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: D:/GitHub/config-repo
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/