server:
  port: 8000
spring:
  application:
    name: cloud-eureka-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址